#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yarg
Version  : 0.1.9
Release  : 2
URL      : https://files.pythonhosted.org/packages/d4/c8/cc640404a0981e6c14e2044fc64e43b4c1ddf69e7dddc8f2a02638ba5ae8/yarg-0.1.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/d4/c8/cc640404a0981e6c14e2044fc64e43b4c1ddf69e7dddc8f2a02638ba5ae8/yarg-0.1.9.tar.gz
Summary  : A semi hard Cornish cheese, also queries PyPI (PyPI client)
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: yarg-license = %{version}-%{release}
Requires: yarg-python = %{version}-%{release}
Requires: yarg-python3 = %{version}-%{release}
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : requests

%description
yarg(1) -- A semi hard Cornish cheese, also queries PyPI
========================================================

%package license
Summary: license components for the yarg package.
Group: Default

%description license
license components for the yarg package.


%package python
Summary: python components for the yarg package.
Group: Default
Requires: yarg-python3 = %{version}-%{release}

%description python
python components for the yarg package.


%package python3
Summary: python3 components for the yarg package.
Group: Default
Requires: python3-core

%description python3
python3 components for the yarg package.


%prep
%setup -q -n yarg-0.1.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551110090
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/yarg
cp LICENSE %{buildroot}/usr/share/package-licenses/yarg/LICENSE
cp LICENSE-REQUESTS %{buildroot}/usr/share/package-licenses/yarg/LICENSE-REQUESTS
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/yarg/LICENSE
/usr/share/package-licenses/yarg/LICENSE-REQUESTS

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
%exclude /usr/lib/python3.7/site-packages/tests/__init__.py
%exclude /usr/lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.pyc
/usr/lib/python3*/*
